# Generated by Django 3.2.6 on 2021-09-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('image', models.URLField()),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Listings',
        ),
    ]
