# Generated by Django 3.2.6 on 2021-09-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210927_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('AU', 'Automotive'), ('BA', 'Babies'), ('BE', 'Beauty'), ('BO', 'Books'), ('EL', 'Electronics'), ('FA', 'Fashion'), ('HE', 'Health'), ('HO', 'Home'), ('SP', 'Sports'), ('OT', 'Other')], max_length=2),
        ),
    ]
