# Generated by Django 3.2.6 on 2021-10-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid_comment_reply_watchlistedlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
