# Generated by Django 3.2.6 on 2021-10-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20211020_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
