# Generated by Django 3.2.6 on 2021-10-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_comment_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
