# Generated by Django 3.2.6 on 2021-10-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_errormessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errormessage',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
